Get CPU cores number test

diff --git a/.github/workflows/get-cpu-cores-test.yaml b/.github/workflows/get-cpu-cores-test.yaml
--- a/.github/workflows/get-cpu-cores-test.yaml
+++ b/.github/workflows/get-cpu-cores-test.yaml
@@ -17,6 +17,7 @@ jobs:
       - name: github-actions-cpu-cores returns
         run: echo ${{ steps.cpu-cores.outputs.count }}
       - name: Get number of CPU cores using script
+        shell: bash
         run: |
           echo "Determining number of cores..."
           if [[ "$RUNNER_OS" == "Linux" ]]; then
@@ -26,8 +27,8 @@ jobs:
           elif [[ "$RUNNER_OS" == "Windows" ]]; then
             CORES=$NUMBER_OF_PROCESSORS
           else
-            echo "Unknown OS. Defaulting to 2 cores."
-            CORES=2
+            echo "Unknown OS. Failing the step."
+            exit 1
           fi
           echo "NUMBER_OF_CORES=$CORES" >> $GITHUB_ENV
           echo "Detected $CORES cores"
